package day_42_Exceptions_Continue;

public class ThrowsKeywords2 {
    public static void main(String[] args) {

        System.out.println("Test is started");
        System.out.println(7/0);

        System.out.println("Test is completed");

    }
}
